name: ThermaNest CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  lint-server:
    name: Lint Node.js Server
    runs-on: ubuntu-latest
    working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint . || true

  lint-dashboard:
    name: Lint Web Dashboard
    runs-on: ubuntu-latest
    working-directory: ./dashboard
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint . || true

  placeholder-firmware:
    name: Firmware Placeholder Job
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "Firmware CI will be added in future stages."
